### YamlMime:ManagedReference
items:
- uid: Bot.Src.Configuration
  commentId: T:Bot.Src.Configuration
  id: Configuration
  parent: Bot.Src
  children:
  - Bot.Src.Configuration.HasBeenLoaded
  - Bot.Src.Configuration.LoadConfig
  - Bot.Src.Configuration.LocalConfig
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: Configuration
  fullName: Bot.Src.Configuration
  type: Class
  source:
    remote:
      path: bot/src/Configuration.cs
      branch: feature/auto-merge
      repo: https://github.com/Coders-Asylum/Bots.git
    id: Configuration
    path: ../bot/src/Configuration.cs
    startLine: 8
  assemblies:
  - Bots
  namespace: Bot.Src
  syntax:
    content: public static class Configuration
    content.vb: Public Module Configuration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Bot.Src.Configuration.LoadConfig
  commentId: M:Bot.Src.Configuration.LoadConfig
  id: LoadConfig
  parent: Bot.Src.Configuration
  langs:
  - csharp
  - vb
  name: LoadConfig()
  nameWithType: Configuration.LoadConfig()
  fullName: Bot.Src.Configuration.LoadConfig()
  type: Method
  source:
    remote:
      path: bot/src/Configuration.cs
      branch: feature/auto-merge
      repo: https://github.com/Coders-Asylum/Bots.git
    id: LoadConfig
    path: ../bot/src/Configuration.cs
    startLine: 31
  assemblies:
  - Bots
  namespace: Bot.Src
  summary: >-
    Loads config from the local config file.


    The config file is expected to be in JSON format and path must be set in the `CONFIG_PATH` env variable.

    This method is called automatically when the Configuration class is initialised, no need of callig it explicitly.
  example: []
  syntax:
    content: public static void LoadConfig()
    content.vb: Public Shared Sub LoadConfig()
  overload: Bot.Src.Configuration.LoadConfig*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: If config env variable is not found or value is null.
  - type: System.Exception
    commentId: T:System.Exception
    description: If the config file contents is null.
- uid: Bot.Src.Configuration.LocalConfig
  commentId: P:Bot.Src.Configuration.LocalConfig
  id: LocalConfig
  parent: Bot.Src.Configuration
  langs:
  - csharp
  - vb
  name: LocalConfig
  nameWithType: Configuration.LocalConfig
  fullName: Bot.Src.Configuration.LocalConfig
  type: Property
  source:
    remote:
      path: bot/src/Configuration.cs
      branch: feature/auto-merge
      repo: https://github.com/Coders-Asylum/Bots.git
    id: LocalConfig
    path: ../bot/src/Configuration.cs
    startLine: 57
  assemblies:
  - Bots
  namespace: Bot.Src
  summary: Returns the local config.
  example: []
  syntax:
    content: public static Dictionary<string, dynamic> LocalConfig { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Object}
      description: A
    content.vb: Public Shared ReadOnly Property LocalConfig As Dictionary(Of String, Object)
  overload: Bot.Src.Configuration.LocalConfig*
- uid: Bot.Src.Configuration.HasBeenLoaded
  commentId: P:Bot.Src.Configuration.HasBeenLoaded
  id: HasBeenLoaded
  parent: Bot.Src.Configuration
  langs:
  - csharp
  - vb
  name: HasBeenLoaded
  nameWithType: Configuration.HasBeenLoaded
  fullName: Bot.Src.Configuration.HasBeenLoaded
  type: Property
  source:
    remote:
      path: bot/src/Configuration.cs
      branch: feature/auto-merge
      repo: https://github.com/Coders-Asylum/Bots.git
    id: HasBeenLoaded
    path: ../bot/src/Configuration.cs
    startLine: 69
  assemblies:
  - Bots
  namespace: Bot.Src
  summary: Flag to check if the config has been loaded.
  example: []
  syntax:
    content: public static bool HasBeenLoaded { get; }
    parameters: []
    return:
      type: System.Boolean
      description: True if the config has already been loaded.
    content.vb: Public Shared ReadOnly Property HasBeenLoaded As Boolean
  overload: Bot.Src.Configuration.HasBeenLoaded*
references:
- uid: Bot.Src
  commentId: N:Bot.Src
  href: Bot.html
  name: Bot.Src
  nameWithType: Bot.Src
  fullName: Bot.Src
  spec.csharp:
  - uid: Bot
    name: Bot
    href: Bot.html
  - name: .
  - uid: Bot.Src
    name: Src
    href: Bot.Src.html
  spec.vb:
  - uid: Bot
    name: Bot
    href: Bot.html
  - name: .
  - uid: Bot.Src
    name: Src
    href: Bot.Src.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.exception
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: Bot.Src.Configuration.LoadConfig*
  commentId: Overload:Bot.Src.Configuration.LoadConfig
  href: Bot.Src.Configuration.html#Bot_Src_Configuration_LoadConfig
  name: LoadConfig
  nameWithType: Configuration.LoadConfig
  fullName: Bot.Src.Configuration.LoadConfig
- uid: Bot.Src.Configuration.LocalConfig*
  commentId: Overload:Bot.Src.Configuration.LocalConfig
  href: Bot.Src.Configuration.html#Bot_Src_Configuration_LocalConfig
  name: LocalConfig
  nameWithType: Configuration.LocalConfig
  fullName: Bot.Src.Configuration.LocalConfig
- uid: System.Collections.Generic.Dictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, dynamic>
  nameWithType: Dictionary<string, dynamic>
  fullName: System.Collections.Generic.Dictionary<string, dynamic>
  nameWithType.vb: Dictionary(Of String, Object)
  fullName.vb: System.Collections.Generic.Dictionary(Of String, Object)
  name.vb: Dictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: dynamic
    name: dynamic
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - name: Object
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Bot.Src.Configuration.HasBeenLoaded*
  commentId: Overload:Bot.Src.Configuration.HasBeenLoaded
  href: Bot.Src.Configuration.html#Bot_Src_Configuration_HasBeenLoaded
  name: HasBeenLoaded
  nameWithType: Configuration.HasBeenLoaded
  fullName: Bot.Src.Configuration.HasBeenLoaded
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
